# Generated by Django 5.0 on 2024-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_alter_creditnote_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotehistory',
            name='hist_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
