# Generated by Django 5.0 on 2024-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_alter_creditnote_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
